name = "playjonny-bonus-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-bonus.es"
HMAC_KEY = "3ded97ad179e10fcb931467f996821b01cf11394cd9d88e075fa3f269b2c14f5"
COOKIE_NAME = "g5v"
PLAY_PATH = "visit"
BUTTON_ID = "pffa01aede700c45a95b91b7a62f1a4b8"
GATE_SALT = "efc4d4591c07c014"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ip13"
CTA_SELECTOR = ".play-button"
